### ISSUE TITLE
My table has disappeared from my site

### ISSUE THREAD

**Issue by greaterlight** [scottpham/tabletop-to-datatables#1]
Hello,
I have used your code on a SquareSpace website. I uploaded graphic.js and tabletop.js directly to the site but all other scripts and css styles are being called. Did any of those files move? What could be the reason that my table disappeared?

**Comment by scottpham** [comment]
Could you explain what you mean by "being called"? Do you mean you are linking directly to the scripts and css files on github?

**Comment by greaterlight** [comment]
Yes. That is correct. However, I fixed the issue. thank you for your
response

www.fullfocusmarketing.com
425-516-8453

**Comment by scottpham** [comment]
While it's likely that something else caused your problem, I would strongly recommend against directly linking to the scripts and css on Github in general, whether with this project or with others. Github is not meant to be used in that way. Also, the file structure and naming conventions of this project can be changed at any time, breaking your code.

Instead, I would recommend downloading the entire project, changing the code that you need, and then uploading to some kind of static file hosting service like Amazon S3

**Comment by greaterlight** [comment]
Great advice. Thank you. I will do that.

www.fullfocusmarketing.com
425-516-8453
