### ISSUE TITLE
Which file contains the path to the Google Sheet?

### ISSUE THREAD

**Issue by greaterlight** [scottpham/tabletop-to-datatables#5]
Hi, I could use a little help. 

I inadvertently moved my clients public Google Sheet that I was pulling into his SquareSpace site. Since I did that, the sheet now has a new URL that I need to call. It has been over a year since I worked with Tabletop To Datatables code. Could someone save me alot of time and headache and remind me in which file do I place the path to my sheet please?

**Comment by scottpham** [comment]
The url or "key" of the public google sheet goes at the top of `graphic.js`: https://github.com/scottpham/tabletop-to-datatables/blob/master/js/graphic.js

**Comment by greaterlight** [comment]
Thanks. I got it working. The issue was that I had skipped the step of "publishing to the web" when I got the new share URL. Hereis how I am using just FYI - this is a Square Space site http://www.seattlebookfair.com/2016-exhibitors-list-new/
