### ISSUE TITLE
Request-Would you please put together a simple read-to-run HTML file?

### ISSUE THREAD

**Issue by egkareem** [scottpham/tabletop-to-datatables#8]
Request-Would you please put together a simple read-to-run HTML file? I am a beginner and I am completely lost. My sheet is: https://docs.google.com/spreadsheets/d/1_YTKcuGpWYro_1KYKTAGjrlrV2chSQwAgKjMBsYcLFE/edit?usp=sharing

**Comment by scottpham** [comment]
Hi there,

The project is about as stripped-down as I could manage. One thing that might trip you up is that you need all the files in this project, not just the HTML file. The HTML file loads the JS file and most of your code goes in there. Give that a shot and follow the instructions very exactly and if that doesn't work let me know what you're seeing.

**Comment by egkareem** [comment]
Thank you for your reply. I will try, and hope that it works.
