### ISSUE TITLE
What do I do if the text in the sheet contains a link?

### ISSUE THREAD

**Issue by Lebihtau** [scottpham/tabletop-to-datatables#9]
I have a data text that contains a url, but after I tried the url it didn't work. how to handle it ?

**Comment by scottpham** [comment]
So you mean that the URL won't display as a hyperlink, correct? Not sure how to fix that specific issue. That's probably a [DataTables](https://datatables.net/) issue.

**Comment by Lebihtau** [comment]
I beg you so that you can help me to solve this problem, I have explored the contents of the js file that you present, but still I don't understand in what section and what line I have to change. This is the third time I have put my head into the wall, please help me :(
